### ISSUE TITLE
is it possible save a script block to psd?

### ISSUE THREAD

**Issue by mazzy-ax** [nightroman/PsdKit#6]
is it possible save a script block to psd?

**Comment by nightroman** [comment]
The short answer is no.

*In theory*, we can add support for this to `ConvertTo-Psd`.

But then, what can we do with the result psd1?
Script blocks are not allowed in psd1 as such.

We cannot import it by `Import-Psd` right away because the used `Import-LocalizedData`
will fail. In theory, we can read the source and create a script block from it.
It's "unsafe" but possible ("unsafe" is up to users after all).

We cannot import it by `Import-PsdXml` now but we probably can add support for this.
Some not so simple work with tokens is needed but it looks possible.

So the long answer is it's possible to support, with some caveats.
But it's a lot of work and the relatively lightweight tool becomes
somewhat heavy. Is it worth it? I am not sure yet.

What are your use cases? Maybe we can find some reasonable workarounds.

**Comment by mazzy-ax** [comment]
I'm agree with 'unsafe'. But maybe you сould think about the analog of the `-SupportedCommand` parameter?

If we talk about deserialization of an `PSObject` from `.psd1`, we have a `Invoke-Expession` cmdlet (it's unsafe at all, agree) or `Import-LocalizedData`/`Import-PowerShellDataFile` (it's highly restricted, i think). I thought `PsdKit` would be perfect for serializing-deserializing of Powershell objects.

**Comment by nightroman** [comment]
OK, it all looks doable with some reasonable effort and not too much overhead for the "normal" psd1.
So it is work in progress. If I do not see problems, it will be supported.

`Import-Psd` will have `-Unsafe` and other commands will support script blocks in their ways.

**Comment by nightroman** [comment]
PsdKit v0.6.0 support script blocks

**Comment by nightroman** [comment]
@mazzy-ax I am sure there are some useful applications of this feature. But I cannot find anything suitable for a sample, not too contrived. Any ideas, perhaps?
